#testedBrowser: CHROME
#testedDataSet: test2
browser:
  #Available browsers: chrome ; firefox ; default: IE
  browserName: chrome
environment:
  test1:
    envName: test1
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: James
    lastName: Hetfield
    email: iron@fist.com
    age: 47
    continent: asia
    message: Form send with success
    command: Browser Commands
    filepath: src/main/resources/file.txt

  test2:
    envName: test2
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: Lars
    lastName: Ulrich
    email: lars@drums.com
    age: 44
    continent: africa
    message: Form send with success
    command: Switch Commands
    filepath: src/main/resources/file.txt

  test3:
    envName: test3
    appUrl: https://seleniumui.moderntester.pl/form.php
    firstName: Kirk
    lastName: Hammet
    email: cry@baby.com
    age: 39
    continent: europe
    message: Form send with success
    command: Wait Commands
    filepath: src/main/resources/file.txt


---